#!/bin/bash
### Where are the ResidualVM tools found?
TP=/home/jjezak/Projects/SummerOfCode2014/residualvm-tools/build
### Where is the EMI data?
DD=/mnt/data/scummvm/Monkey\ Island\ 4

### Code
p=$(pwd)
mkdir /tmp/dumpdir
cd /tmp/dumpdir && $TP/unlab "${DD}"/local.m4b > /dev/null
cp /tmp/dumpdir/$1 $p
rm -rf /tmp/dumpdir
cd $p
$TP/delua $1 > $1.tmp
mv $1.tmp $1
